/* tslint:disable */
/* eslint-disable */
/**
 * Dual-System Digital Twin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response payload containing the simulation history.
 * @export
 * @interface HistoryResponse
 */
export interface HistoryResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof HistoryResponse
     */
    history: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the HistoryResponse interface.
 */
export function instanceOfHistoryResponse(value: object): value is HistoryResponse {
    if (!('history' in value) || value['history'] === undefined) return false;
    return true;
}

export function HistoryResponseFromJSON(json: any): HistoryResponse {
    return HistoryResponseFromJSONTyped(json, false);
}

export function HistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'history': json['history'],
    };
}

export function HistoryResponseToJSON(json: any): HistoryResponse {
    return HistoryResponseToJSONTyped(json, false);
}

export function HistoryResponseToJSONTyped(value?: HistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'history': value['history'],
    };
}

