/* tslint:disable */
/* eslint-disable */
/**
 * Dual-System Digital Twin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response payload containing the simulation logs.
 * @export
 * @interface LogsResponse
 */
export interface LogsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof LogsResponse
     */
    logs: Array<string>;
}

/**
 * Check if a given object implements the LogsResponse interface.
 */
export function instanceOfLogsResponse(value: object): value is LogsResponse {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function LogsResponseFromJSON(json: any): LogsResponse {
    return LogsResponseFromJSONTyped(json, false);
}

export function LogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'],
    };
}

export function LogsResponseToJSON(json: any): LogsResponse {
    return LogsResponseToJSONTyped(json, false);
}

export function LogsResponseToJSONTyped(value?: LogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'],
    };
}

