/* tslint:disable */
/* eslint-disable */
/**
 * Dual-System Digital Twin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for resetting a simulation session.
 * 
 * Attributes:
 *     session_id (UUID): The session identifier.
 *     params (dict, optional): New model parameters for reset.
 * @export
 * @interface ResetRequest
 */
export interface ResetRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetRequest
     */
    sessionId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ResetRequest
     */
    params?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ResetRequest interface.
 */
export function instanceOfResetRequest(value: object): value is ResetRequest {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function ResetRequestFromJSON(json: any): ResetRequest {
    return ResetRequestFromJSONTyped(json, false);
}

export function ResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function ResetRequestToJSON(json: any): ResetRequest {
    return ResetRequestToJSONTyped(json, false);
}

export function ResetRequestToJSONTyped(value?: ResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session_id': value['sessionId'],
        'params': value['params'],
    };
}

