/* tslint:disable */
/* eslint-disable */
/**
 * Dual-System Digital Twin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response payload containing the current state of the simulation.
 * @export
 * @interface StateResponse
 */
export interface StateResponse {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StateResponse
     */
    state: { [key: string]: any; };
}

/**
 * Check if a given object implements the StateResponse interface.
 */
export function instanceOfStateResponse(value: object): value is StateResponse {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function StateResponseFromJSON(json: any): StateResponse {
    return StateResponseFromJSONTyped(json, false);
}

export function StateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
    };
}

export function StateResponseToJSON(json: any): StateResponse {
    return StateResponseToJSONTyped(json, false);
}

export function StateResponseToJSONTyped(value?: StateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
    };
}

