/* tslint:disable */
/* eslint-disable */
/**
 * Dual-System Digital Twin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request payload for advancing a simulation by one step.
 * 
 * Attributes:
 *     session_id (UUID): The session identifier.
 *     control_input (Any): The control input for the model.
 *     delta_time (float, optional): Time step duration. Defaults to 1.0.
 * @export
 * @interface StepRequest
 */
export interface StepRequest {
    /**
     * 
     * @type {string}
     * @memberof StepRequest
     */
    sessionId: string;
    /**
     * 
     * @type {number}
     * @memberof StepRequest
     */
    controlInput: number;
    /**
     * 
     * @type {number}
     * @memberof StepRequest
     */
    deltaTime?: number;
}

/**
 * Check if a given object implements the StepRequest interface.
 */
export function instanceOfStepRequest(value: object): value is StepRequest {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('controlInput' in value) || value['controlInput'] === undefined) return false;
    return true;
}

export function StepRequestFromJSON(json: any): StepRequest {
    return StepRequestFromJSONTyped(json, false);
}

export function StepRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'controlInput': json['control_input'],
        'deltaTime': json['delta_time'] == null ? undefined : json['delta_time'],
    };
}

export function StepRequestToJSON(json: any): StepRequest {
    return StepRequestToJSONTyped(json, false);
}

export function StepRequestToJSONTyped(value?: StepRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session_id': value['sessionId'],
        'control_input': value['controlInput'],
        'delta_time': value['deltaTime'],
    };
}

